head: 'wass-well-final'
dataset:
        name: 'wass'
        fcn_mu: '[2*x*(1-x**2)]'
        x_init: [0]
        n_points: 1000
        n_test: 100
        batch_size: 800
        t0: 0
        tn: 10
        num_digits: 0
        background: True
        mnist: False
        nc: 3
        affine: False
n_tries: 3
ae:
        path: Null
        lr: 0.001
        net:
                in_channels: 3
                width: 8
                latent_dim: 1
                add_det: 0
                use_skip: False
                loss: 'exact'
                sig_x: 0.05
                pz_var: 0
                sig_det: 0.001
                sigma_type: 'diag'
sde:
        type: 'const-sig'
        act: 'nn.Softplus'
        path: Null
        width: 16
        depth: 4
        lr_mu: 0.001
        lr_sigma: 0
optimizer:
        name: 'Adam'
        sched: 'ExponentialLR'
        lr: 0.0001
        sched_param:
                gamma: 0.999
        n_epochs: 500

